/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 isometric_japanese_tea_room.glb 
Author: raghaviyer (https://sketchfab.com/raghaviyer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/isometric-japanese-tea-room-b422c6839b72424ead4c015596c5a7d5
Title: Isometric Japanese tea room
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function JapanRoom(props) {
  const { nodes, materials } = useGLTF('/models/isometric_japanese_tea_room.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={[1.309, 1.309, 0.205]}>
          <mesh geometry={nodes.Cube_0.geometry} material={materials['wood_floor.001']} />
          <mesh geometry={nodes.Cube_1.geometry} material={materials['wood.004']} />
          <mesh geometry={nodes.Cube_2.geometry} material={materials['wall_painting.001']} />
          <mesh geometry={nodes.Cube_3.geometry} material={materials['wood.001']} />
          <mesh geometry={nodes.Cube_4.geometry} material={materials.tea_table_wood} />
          <mesh geometry={nodes.Cube_5.geometry} material={materials.Point} />
          <mesh geometry={nodes.Cube_6.geometry} material={materials['wall.001']} />
          <mesh geometry={nodes.Cube_7.geometry} material={materials['wood.003']} />
          <mesh geometry={nodes.Cube_8.geometry} material={materials.blue_pillow} />
          <mesh geometry={nodes.Cube_9.geometry} material={materials.pink_oilliw} />
          <mesh geometry={nodes.Cube_10.geometry} material={materials['Lamp.001']} />
          <mesh geometry={nodes.Cube_11.geometry} material={materials.pale_green} />
          <mesh geometry={nodes.Cube_12.geometry} material={materials['wa.001']} />
          <mesh geometry={nodes.Cube_13.geometry} material={materials.fllor_mat} />
          <mesh geometry={nodes.Cube_14.geometry} material={materials.mat_border} />
          <mesh geometry={nodes.Cube_15.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Cube_16.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Cube_17.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Cube_18.geometry} material={materials['Material.012']} />
          <mesh geometry={nodes.Cube_19.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cube_20.geometry} material={materials.baby_pink} />
          <mesh geometry={nodes.Cube_21.geometry} material={materials.leaf} />
          <mesh geometry={nodes.Cube_22.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cube_23.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Cube_24.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Cube_25.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Cube_26.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.Cube_27.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Cube_28.geometry} material={materials['Material.014']} />
          <mesh geometry={nodes.Cube_29.geometry} material={materials.Material} />
          <mesh geometry={nodes.Cube_30.geometry} material={materials['tea_cups.001']} />
          <mesh geometry={nodes.Cube_31.geometry} material={materials.teapot_holder} />
          <mesh geometry={nodes.Cube_32.geometry} material={materials.mixer} />
          <mesh geometry={nodes.Cube_33.geometry} material={materials.bowl} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/isometric_japanese_tea_room.glb')
